---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html/
    - /bin/cp landing/index.html $DEPLOYPATH
    - /bin/cp landing/style.css $DEPLOYPATH
    - /bin/cp landing/script.js $DEPLOYPATH
    - /bin/cp landing/tailwind-compiled.css $DEPLOYPATH
    - /bin/cp landing/robots.txt $DEPLOYPATH
    - /bin/cp landing/sitemap.xml $DEPLOYPATH
    - /bin/cp landing/favicon.ico $DEPLOYPATH
    - /bin/cp landing/apple-touch-icon.png $DEPLOYPATH
    - /bin/cp landing/site.webmanifest $DEPLOYPATH
    - /bin/cp -R landing/img $DEPLOYPATH