---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/etc/invoo.es/
    - /bin/rm -f $DEPLOYPATH/index.html $DEPLOYPATH/style.css $DEPLOYPATH/script.js
    - /bin/cp landing/index.html $DEPLOYPATH
    - /bin/cp landing/style.css $DEPLOYPATH
    - /bin/cp landing/script.js $DEPLOYPATH
    - /bin/cp landing/robots.txt $DEPLOYPATH
    - /bin/cp landing/sitemap.xml $DEPLOYPATH
    - /bin/cp landing/favicon.ico $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/img $DEPLOYPATH/docs $DEPLOYPATH/scripts
    - /bin/cp -R landing/img $DEPLOYPATH
    - /bin/cp -R landing/docs $DEPLOYPATH
    - /bin/cp -R landing/scripts $DEPLOYPATH