---
deployment:
  tasks:
    - /bin/cp landing/index.html $HOME/public_html/
    - /bin/cp landing/style.css $HOME/public_html/
    - /bin/cp landing/script.js $HOME/public_html/
    - /bin/cp landing/tailwind-compiled.css $HOME/public_html/
    - /bin/cp landing/robots.txt $HOME/public_html/
    - /bin/cp landing/sitemap.xml $HOME/public_html/
    - /bin/cp landing/favicon.ico $HOME/public_html/
    - /bin/cp landing/apple-touch-icon.png $HOME/public_html/
    - /bin/cp landing/site.webmanifest $HOME/public_html/
    - /bin/cp -R landing/img $HOME/public_html/