---
deployment:
  tasks:
    # Set deployment path
    - export DEPLOYPATH=/home/$USER/public_html/
    
    # Clean up existing landing page files
    - /bin/rm -f $DEPLOYPATH/index.html
    - /bin/rm -f $DEPLOYPATH/style.css
    - /bin/rm -f $DEPLOYPATH/script.js
    - /bin/rm -f $DEPLOYPATH/robots.txt
    - /bin/rm -f $DEPLOYPATH/sitemap.xml
    - /bin/rm -f $DEPLOYPATH/favicon.ico
    - /bin/rm -f $DEPLOYPATH/apple-touch-icon.png
    - /bin/rm -rf $DEPLOYPATH/img
    - /bin/rm -rf $DEPLOYPATH/docs
    - /bin/rm -rf $DEPLOYPATH/scripts
    
    # Deploy all landing page content
    - /bin/cp landing/index.html $DEPLOYPATH
    - /bin/cp landing/style.css $DEPLOYPATH
    - /bin/cp landing/script.js $DEPLOYPATH
    - /bin/cp landing/robots.txt $DEPLOYPATH
    - /bin/cp landing/sitemap.xml $DEPLOYPATH
    - /bin/cp landing/favicon.ico $DEPLOYPATH
    - /bin/cp landing/apple-touch-icon.png $DEPLOYPATH
    
    # Deploy directories
    - /bin/cp -R landing/img $DEPLOYPATH
    - /bin/cp -R landing/docs $DEPLOYPATH
    - /bin/cp -R landing/scripts $DEPLOYPATH
    
    # Set proper permissions for web content
    - /bin/chmod 644 $DEPLOYPATH/index.html
    - /bin/chmod 644 $DEPLOYPATH/style.css
    - /bin/chmod 644 $DEPLOYPATH/script.js
    - /bin/chmod 644 $DEPLOYPATH/robots.txt
    - /bin/chmod 644 $DEPLOYPATH/sitemap.xml
    - /bin/chmod 644 $DEPLOYPATH/favicon.ico
    - /bin/chmod 644 $DEPLOYPATH/apple-touch-icon.png
    - /bin/chmod -R 644 $DEPLOYPATH/img/*
    - /bin/chmod 755 $DEPLOYPATH/img
    - /bin/chmod 755 $DEPLOYPATH/docs
    - /bin/chmod 755 $DEPLOYPATH/scripts