---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html/
    - /bin/cp landing/index.html $DEPLOYPATH
    - /bin/cp landing/style.css $DEPLOYPATH
    - /bin/cp landing/script.js $DEPLOYPATH
    - /bin/cp -R landing/img $DEPLOYPATH